export {
  getDatabaseConfig,
  getDatabaseConfigurationStatus,
} from "./config";

// Persistence callers should import repository operations from this public
// boundary rather than importing Drizzle, libSQL, or adapters directly.
export {
  addExistingPlayerToLeagueForUser,
  assignGameNightPhysicalBoardsForUser,
  addLeaguePlayerToSeasonForUser,
  archivePlayer,
  assignGameNightPlayerToTeamForUser,
  authenticateBoardDeviceCredential,
  BoardDeviceAssignmentError,
  BoardDeviceCredentialError,
  createGameNightForUser,
  createGameNightTemplateForUser,
  createLeagueForUser,
  createLeaguePlayerForUser,
  createSeasonForUser,
  createPhysicalBoardForUser,
  createVenueForLeagueForUser,
  deleteEmptyVenueForUser,
  getAppMetadata,
  getBoardDeviceAssignment,
  getBoardDeviceConnectionForCredential,
  getBoardDeviceMatchForCredential,
  getDefaultGameNightTemplateForUser,
  getGameNightForUser,
  getGameNightTemplateForUser,
  getVenueHardwareForUser,
  getLeagueMatchForUser,
  getPlayerById,
  hydrateGameNightAutoLayout,
  hydrateGameNightAutoLayouts,
  LeagueMatchStateError,
  LeaguePermissionError,
  listBoardDevicesForUser,
  listGameNightsForUser,
  listGameNightTemplatesForUser,
  listLeaguePlayersForUser,
  linkVenueToLeagueForUser,
  listAdminVenuesForUser,
  listLeaguesForUser,
  listPhysicalBoardsForVenueForUser,
  listVenuesForLeagueForUser,
  listPlayerDirectoryForUser,
  listPlayers,
  listRecentX01MatchSummaries,
  listX01MatchArchivesForUser,
  MatchOwnershipError,
  optimizeSettingsForGameNight,
  pingDatabase,
  populateGameNightBoardsForUser,
  prepareGameNightTeamsForUser,
  refreshGameNightForUser,
  regenerateGameNightRoundForUser,
  registerBoardDeviceForUser,
  removeLeaguePlayerFromSeasonForUser,
  replaceGameNightRoundFixturesForUser,
  rotateBoardDeviceKeyForUser,
  savePlayer,
  saveX01MatchArchive,
  saveX01MatchArchiveForUser,
  setAppMetadata,
  setGameNightStatusForUser,
  setGameNightVenueForUser,
  setGameNightTeamStatusForUser,
  startBoardDeviceMatchForCredential,
  startLeagueMatchForUser,
  startNextGameNightRoundForUser,
  submitBoardDeviceTurnForCredential,
  submitLeagueMatchTurnForUser,
  syncAutomaticGameNightLayout,
  undoBoardDeviceTurnForCredential,
  undoLastLeagueMatchTurnForUser,
  unlinkVenueFromLeagueForUser,
  updateBoardDeviceForUser,
  updatePhysicalBoardForUser,
  updateGameNightAttendanceForUser,
  updateGameNightSettingsForUser,
  updateGameNightTemplateForUser,
  updateVenueForUser,
  type AddExistingPlayerToLeagueForUserInput,
  type CreateGameNightForUserInput,
  type CreateGameNightTemplateForUserInput,
  type CreateLeagueForUserInput,
  type CreateLeaguePlayerForUserInput,
  type CreateSeasonForUserInput,
  type MutateSeasonRosterForUserInput,
  type SavePlayerInput,
  type UpdateGameNightAttendanceForUserInput,
  type UpdateGameNightSettingsForUserInput,
  type UpdateGameNightTemplateForUserInput,
} from "./repositories";
