export {
  getDatabaseConfig,
  getDatabaseConfigurationStatus,
} from "./config";

// Persistence callers should import repository operations from this public
// boundary rather than importing Drizzle, libSQL, or adapters directly.
export {
  addLeaguePlayerToSeasonForUser,
  archivePlayer,
  assignGameNightPlayerToTeamForUser,
  createGameNightForUser,
  createLeagueForUser,
  createLeaguePlayerForUser,
  createSeasonForUser,
  getAppMetadata,
  getGameNightForUser,
  getLeagueMatchForUser,
  getPlayerById,
  LeagueMatchStateError,
  LeaguePermissionError,
  listGameNightsForUser,
  listLeaguePlayersForUser,
  listLeaguesForUser,
  listPlayers,
  listRecentX01MatchSummaries,
  listX01MatchArchivesForUser,
  MatchOwnershipError,
  pingDatabase,
  populateGameNightBoardsForUser,
  prepareGameNightTeamsForUser,
  removeLeaguePlayerFromSeasonForUser,
  savePlayer,
  saveX01MatchArchive,
  saveX01MatchArchiveForUser,
  setAppMetadata,
  setGameNightStatusForUser,
  startLeagueMatchForUser,
  submitLeagueMatchTurnForUser,
  undoLastLeagueMatchTurnForUser,
  updateGameNightAttendanceForUser,
  updateGameNightSettingsForUser,
  type CreateGameNightForUserInput,
  type CreateLeagueForUserInput,
  type CreateLeaguePlayerForUserInput,
  type CreateSeasonForUserInput,
  type MutateSeasonRosterForUserInput,
  type SavePlayerInput,
  type UpdateGameNightAttendanceForUserInput,
  type UpdateGameNightSettingsForUserInput,
} from "./repositories";
